name: wimpillay_main
description: Proyecto con login de Google y Firebase integrado.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ðŸ”¥ Firebase base
  firebase_core: ^3.6.0
  # ðŸ”‘ AutenticaciÃ³n con Firebase
  firebase_auth: ^5.3.1
  # â˜ï¸ Base de datos Firestore
  cloud_firestore: ^5.4.4
  # ðŸ”µ Login con Google
  google_sign_in: ^6.2.1

  qr_flutter: ^4.1.0
  
  mobile_scanner: ^5.2.3

  intl: ^0.19.0
  http: ^1.2.1

  cupertino_icons: ^1.0.8
  
  # --- NUEVAS DEPENDENCIAS ---
  image_picker: ^1.1.2           # Para seleccionar la captura de pantalla
  google_mlkit_text_recognition: ^0.13.0  # El cerebro que lee el texto
  gal: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/google_logo.png
    - assets/qr_yape.jpg
    
flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"
  